# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rasa-test:
    name: Build RASA bot
    runs-on: ubuntu-latest
    steps:
      # Checks-out GitHub repository
      # more: https://github.com/actions/checkout
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Cache the dependecies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('requirements.txt') }}
      - name: Install python dependencies
        run: |
          pip3 install -r requirements.txt
      - name: Train RASA model
        run: |
          rasa train
      - name: Test built model
        run: |
          rasa test
      - name: Archive built RASA model
        uses: actions/upload-artifact@v2
        with:
          name: models
          path: |
            models

